name: Type checker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Authorize this repo to install from the siglent_emulator repo
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SIGLENT_EMULATOR_REPO_PRIVATE_SSH_KEY }}'

        python -m pip install --upgrade pip
        python -m pip install mypy
        python -m pip install -r requirements.txt
        python -m pip install git+ssh://git@github.com/BoundlessScience/siglent_emulator
    - name: Analyzing source code with mypy
      run: |
        python -m mypy src/
        python -m mypy tests/
